######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 24 13:58:10 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../main/
#DEPENDPATH += /home/jakob/workspace/vhc/bin/main
unix:LIBS += -L/home/jakob/workspace/vhc/bin/main -lvhc

# Input
SOURCES += Main.cc
